# permissions for end users to view exercises.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exercise-viewer-role
rules:
- apiGroups:
  - exercise.vangelovj
  resources:
  - exercises
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - exercise.vangelovj
  resources:
  - exercises/status
  verbs:
  - get
