# permissions for end users to edit exercises.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exercise-editor-role
rules:
- apiGroups:
  - exercise.vangelovj
  resources:
  - exercises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - exercise.vangelovj
  resources:
  - exercises/status
  verbs:
  - get
